# Generated by Django 4.0.5 on 2022-06-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_event_name', models.CharField(max_length=100)),
                ('banner_event_image', models.ImageField(blank=True, upload_to='banner_event_media')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
